### ISSUE TITLE
DB생성 관련해 여쭤볼게있습니다.

### ISSUE THREAD

**Issue by roharon** [JungWinter/HongikFood#14]
python run.py (혹은 python run.py migrate)을 하게될경우 
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: menu [SQL: 'SELECT menu.id AS menu_id, menu.date AS menu_date, menu.place AS menu_place, menu.time AS menu_time, menu.menu AS menu_menu \nFROM menu \nWHERE menu.place = ? AND menu.date = ? AND menu.time = ?\n LIMIT ? OFFSET ?'] [parameters: ('학생회관', '2017.02.06', '저녁', 1, 0)]

이러한 에러가 나옵니다.
어떻게 해결해야될지 알수있을까요?

**Comment by JungWinter** [comment]
이슈 감사합니다!
혹시 DB는 생성되어있나요? 제가 README에 적어두지 않았는데
스키마에 맞는 DB가 존재해야 정상작동합니다.
프로젝트 루트 디렉토리에서 파이썬 쉘을 실행시켜
```python
>>> from app import db
>>> db.create_all()
```
명령어를 통해 DB를 생성시킬 수 있습니다.

**Comment by JungWinter** [comment]
확인해보니 의존관계가 꼬여있었네요
462f97e22e7b30ef0962d94cacba8f52574e07b9 커밋을 통해 app폴더의 `__init__.py` 파일에서 `db.create_all()` 구문을 추가하고  `models`의 import순서를 바꿔 해결했습니다. 
학식알리미가 아닌 새로운 프로젝트를 만드시는 거라면 [yellowid api flask구현체](https://github.com/JungWinter/yellowid-flask)를 참고하셔도 좋습니다.

**Comment by roharon** [comment]
정상적으로 실행이 되나, API테스트를 하게될 경우 404 not found를 나타내고있습니다.
Django 기준으로 알기엔 http:// .:포트/~ 에 접속하면 url 파일에 접속되어 keyboard,message 등등을 출력하는 것으로 아는데 JungWinter 님의 자료는 어떻게하여 keyboard와 같은파일을 불러오는건가요...?
실력이 많이 미숙해 배우는 단계라 너그럽게 이해해주셨으면 합니다

**Comment by JungWinter** [comment]
> 정상적으로 실행이 되나, API테스트를 하게될 경우 404 not found를 나타내고있습니다.
> Django 기준으로 알기엔 http:// .:포트/~ 에 접속하면 url 파일에 접속되어 keyboard,message 등등을 출력하는 것으로 아는데 JungWinter 님의 자료는 어떻게하여 keyboard와 같은파일을 불러오는건가요...?
> 실력이 많이 미숙해 배우는 단계라 너그럽게 이해해주셨으면 합니다

라고 달아주신거 같은데 어디에 있는지 안보이네용
질문은 언제나 환영입니다!
해당 증상은 아마 `__init__.py`파일에 `from app import views`구문이 없어서 나타나는 증상 같습니다.
순환 참조 오류를 방지하기 위해 파일의 밑부분에 적어주시면 해결될 듯 합니다
