### ISSUE TITLE
안녕하세요 메일 남겼던 학생입니다 !

### ISSUE THREAD

**Issue by clsrn919** [JungWinter/HongikFood#15]
파이썬으로 홍대 서울캠 식단 html 또는 다른사이트를 읽어 원하는 부분을 명령창에 띄우는건 되는데

홍대 세종캠 식단 html 을 읽으려 하면 에러가 뜨내요..
HTTP Error 400 : Bad Request 이라는데 구글검색으로 해결법 찾아봐도 잘 모르겠습니다..
이런 오류가 왜 뜨는지도 잘 모르겠구요..

파이썬 코드 -----------------------------------------------

from bs4 import BeautifulSoup
from urllib.request import urlopen

html = urlopen("http://sj.hongik.ac.kr/site/food/food_menu.html")

source = html.read()
html.close()
soup = BeautifulSoup(source, "lxml")

table_div = soup.find('tbody')
tables = table_div.find_all(class_="mon")
menu = tables[0]
#table = menu.find_all('p')

print(tables[0])

----------------------------------------------------------

**Comment by JungWinter** [comment]
해당 오류는 `Request`에 `Header`를 지정해 주지 않아서 발생한 오류입니다.
[URL](http://sj.hongik.ac.kr/site/food/food_menu.html)을 개발자도구로 조사해보면 `Request header`에 여러 값들이 들어가있음을 확인할 수 있습니다.
여기서 필수적으로 들어가야 하는 헤더정보는 `User-Agent`와 `Accept`입니다.
따라서 요청을 보낼 때 코드에 아래와 같은 더미 헤더를 추가해주셔야합니다.
```
User-Agent: Mozilla/5.0
Accept: text/html
```

코드 상으론 다음과 같습니다.
```python
from urllib.request import Request, urlopen
req = Request('http://sj.hongik.ac.kr/site/food/food_menu.html')
req.add_header('User-Agent', 'Mozilla/5.0')
req.add_header('Accept', 'text/html')
source = urlopen(req).read()
```
혹은 [urllib.request](https://docs.python.org/3/library/urllib.request.html#urllib.request.Request) 문서의 api를 참고해
```python
url = "http://sj.hongik.ac.kr/site/food/food_menu.html"
req = Request(
    url,
    data=None,
    headers={
        "User-Agent": "Mozilla/5.0",
        "Accept": "text/html"
    }
)
source = urlopen(req).read()
```
로 사용하실수도 있습니다.
